export interface Kenteken {
    "Aanhangwagen autonoom geremd"?: null;
    "Retrofit roetfilter"?: null | string;
    Voertuigsoort?: string;
    "Aantal cilinders"?: number;
    "@version"?: string;
    "Aantal staanplaatsen"?: null;
    "Aantal wielen"?: number;
    "Europese voertuigcategorie"?: string;
    Wielbasis?: number;
    "Openstaande terugroepactie indicator"?: string;
    "Bruto BPM"?: number | null;
    Kenteken?: string;
    Variant?: string;
    "API Gekentekende_voertuigen_brandstof"?: string;
    Breedte?: number;
    "Eerste kleur"?: string;
    eersteKleur: "Eerste kleur";
    "Vermogen (brom/snorfiets)"?: number | null;
    "Vervaldatum APK"?: null | string;
    "Maximum massa trekken ongeremd"?: number | null;
    "Europese voertuigcategorie toevoeging"?: null | string;
    "API Gekentekende_voertuigen_carrosserie"?: string;
    "Aantal deuren"?: number;
    "Toegestane maximum massa voertuig"?: number;
    Merk?: string;
    "Oplegger geremd"?: null;
    "Vervaldatum tachograaf"?: null;
    "Maximale constructiesnelheid (brom/snorfiets)"?: number | null;
    path?: string;
    "Aantal rolstoelplaatsen"?: number;
    "Taxi indicator"?: string;
    "Maximum trekken massa geremd"?: number | null;
    Zuinigheidslabel?: null | string;
    "Technische max. massa voertuig"?: number;
    "Type gasinstallatie"?: null;
    Typegoedkeuringsnummer?: string;
    "Volgnummer wijziging EU typegoedkeuring"?: number;
    "Maximum massa samenstelling"?: number;
    Cilinderinhoud?: number;
    "Wacht op keuren"?: string;
    Laadvermogen?: null;
    "Aanhangwagen middenas geremd"?: null;
    "WAM verzekerd"?: string;
    message?: string;
    Inrichting?: string;
    "Plaats chassisnummer"?: string;
    Type?: null | string;
    "Export indicator"?: string;
    "Massa rijklaar"?: number;
    "Afstand hart koppeling tot achterzijde voertuig"?: number;
    "Datum tenaamstelling"?: string;
    host?: string;
    "API Gekentekende_voertuigen_voertuigklasse"?: string;
    "Vermogen massarijklaar"?: number;
    Lengte?: number;
    "Europese uitvoeringcategorie toevoeging"?: null | string;
    "Tweede kleur"?: string;
    "Aantal zitplaatsen"?: number;
    "Massa ledig voertuig"?: number;
    "Afwijkende maximum snelheid"?: null;
    "Maximum ondersteunende snelheid"?: null;
    "Datum eerste afgifte Nederland"?: string;
    Handelsbenaming?: string;
    "API Gekentekende_voertuigen_carrosserie_specifiek"?: string;
    "Datum eerste toelating"?: string;
    Catalogusprijs?: null | string;
    "API Gekentekende_voertuigen_assen"?: string;
    "@timestamp"?: Date;
    Uitvoering?: string;
    "Afstand voorzijde voertuig tot hart koppeling"?: number;
}

export interface KentekenSource {
    source: Kenteken;
}